### ISSUE TITLE
[Oct 9] Generate a link that Judges can visit to set the platforms they can judge on

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#105]
We'd like for Judges to be able to set the platforms that they own so we can match them up with games better.

We're sending out an email to the judges soon, would be great to include a generated link that they can visit so they can set the platforms that they own.  

If this can happen before the 9th, that would be great, but not required.

**Comment by kitsuta** [comment]
@LowPolyCount, is this the email you wanted updated? https://github.com/magfest/mivs/blob/master/mivs/templates/emails/judge_intro.txt

**Comment by LowPolyCount** [comment]
@kitsuta we can include the link either on that one if it's done before we send or can create a new one.
