### ISSUE TITLE
ERROR validating game platforms on submission

### ISSUE THREAD

**Issue by RobRuana** [magfest/mivs#110]
Report from a game studio:
 
> I’m having some issues submitting my round 2 build for Magfest.  I’ve supplied a link and filled out all of the necessary categories and when I go to submit or save the information I get a prompt that I haven’t filled out the target platform for the build.  This is understandable but there is no where on the web page to submit this information. I’ve provided some screen shots to show you what I mean.  I’ve also looked at the page on Edge and Chrome so I don’t think it’s a browser issue.

<img width="320" alt="capture" src="https://user-images.githubusercontent.com/2592431/31236864-4d4b4724-a9c3-11e7-99e4-391409e80a19.PNG">
<img width="320" alt="capture2" src="https://user-images.githubusercontent.com/2592431/31236922-7b9d7b92-a9c3-11e7-9a51-c651ace8bfad.PNG">

**Comment by RobRuana** [comment]
Okay, I think I know what is happening with these games. The `platform` attribute was not added to games until September 5. (See here https://github.com/magfest/mivs/pull/96). Any games created before September 5 won't have a `platform` selected, and will fail the validation checks. The `platform` selection field is on a different page than the pages shown in the original screenshots. We run the validations any time a game is saved, which is why the error is popping up on a screen that does not include any `platform` selection fields.

There are two solutions to this issue:
1. We can disable the `platform` validations in the Uber code (_I don't really like this idea, but if this becomes a broader problem we can do it anyway_)
2. The game studios can go back to the game "Edit" screen and select the platforms for their game (_see attached screenshot_)

Thoughts?

<img width="915" alt="screen shot 2017-10-05 at 11 55 23 am" src="https://user-images.githubusercontent.com/2592431/31237785-e7d501de-a9c5-11e7-9ab1-82dd02e1feed.png">

**Comment by kitsuta** [comment]
Ooh, good sleuthing! I think you're right.

This is fine right now but as soon as the deadline passes on Oct 9th it's gonna be a real problem -- that edit button disappears for all non-admins.

I guess the best thing to do would be to find any games that don't have platforms and ask the studios to fill out the platforms for those games. Then as a last resort we can disable that validation on the 9th, if any studios are still missing platforms.

**Comment by kitsuta** [comment]
OK, according to a DB pull @RobRuana did, there are 43(!) games without platforms listed.

@LowPolyCount do you want an email coded up to send to studios with games that need to add platforms, so they can fill those out? Or would you rather we just disable the validation for this year and call the platform-matching a 'next year' feature?

**Comment by RobRuana** [comment]
We _could_ add something like "Unknown" to `platforms_text` to get those games to pass validation. We'd effectively be making the `platforms` feature very unhelpful for those 43 games, but at least the studios wouldn't run into this issue.

**Comment by RobRuana** [comment]
FYI, we've set `platforms_text` to "Unknown" for all the games that did not already have platforms set. Thus, we should not encounter this error anymore.
