### ISSUE TITLE
[Sep 16] Admins should be able to edit submitted games

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/mivs#12]
We currently have some validations which prevent entries from being edited after the deadline.

We should add an exception for if the person doing the editing is also a logged-in MIVS Admin then we should allow it, since that will allow admins to add corrections/notes to show all the judges even after the deadline.

**Comment by timrxd** [comment]
mivs_apps/index line 70, may already be done

**Comment by RobRuana** [comment]
Need to verify this is done...

**Comment by kitsuta** [comment]
Tested this in my local copy, it's already been done!
