### ISSUE TITLE
Judges not able to play working games

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/mivs#15]
Judges currently have a way to report games as being broken, e.g. if the link doesn't work or the build won't load.

However, sometimes a judge is assigned a game and realizes that it's an iOS game and they use Android, or that the game won't play on a Mac, or something.

We should add some other options they can use to indicate issues like this back to the MIVS admins.

**Comment by kitsuta** [comment]
This already got implemented some time ago as `c.COULD_NOT_PLAY`.
