### ISSUE TITLE
Button to approve feedback disabled based on game's status

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#150]
We're having trouble approving feedback for games with the following status:
"round one" and "declined"

All others seem to work ok that we've seen for now.

**Comment by LowPolyCount** [comment]
Would it be possible to prioritize fixing this?  There are a couple games we'd have to email out feedback manually for without a fix for this.

**Comment by RobRuana** [comment]
Ugh, thanks for your patience. I'll be able to get this pushed out either tomorrow evening, or Thursday morning.

**Comment by RobRuana** [comment]
The fix for this should be live!

Thanks again for your patience! Super really knocked the wind outta me 😄
