### ISSUE TITLE
[Sep 3] As an admin, I'd like to match judges to games based on hardware

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/mivs#17]
Some judges have android, some have iOS, some have high-end PCs some have XBoxes, etc.  Some games work on some of those platforms but not others.

We should add the ability for games to specify their platforms, and for judges to specify what platforms they support.  This would probably replace the genre matching we do now, since that currently isn't being used, though we should confirm this with the MIVS folks before implementing it.

**Comment by LowPolyCount** [comment]
To do this, I'm envisioning that we have checkboxes for the platforms we're supporting this year.  Judges will also need those checkboxes on a page so they can list their platforms. 

Oh, and then it'd be helpful to have a list of judges who are compatable with the game's platform for when we go to assign them.  (That doesn't need to happen until Phase 2 closes and judging begins)

Assume any game/judge that doesn't check anything can be judged by anyone, or we can at least make sure games have one category checked.

**Comment by LowPolyCount** [comment]
We should have checkboxes and tell indies "Please check all platforms that your game will be playable on"

PC
PC using a gamepad
Nintendo Switch
Xbox One
Playstation 4
Playstation 4 VR
Android
IOS
Oculus Rift
HTC Vive
Other (Contains a textfield they can write in)
