### ISSUE TITLE
[Nov 5] Calculate due date sent with acceptance emails

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#32]
When sending emails to indies that they've been accepted into the showcase but that they still need to confirm, we manually set a date in the email that they need to confirm by.  

It would be great if we can add a way to calculate the date a certain time from when the email is sent.  This way, when an indie is bumped from waitlist to accept, the correct date for them will show instead of us having to say, "Forget the date given below"

**Comment by EliAndrewC** [comment]
Seems reasonable and easy to implement :)
