### ISSUE TITLE
Export information on games accepted into MIVS into multiple formats

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#35]
After MIVS games have been chosen, we have to hand create data culled from the chosen games. This data is used in the following places:
- MIVS Website
- GuideBook

It would be create if the data could be created for us by the system.

**Comment by EliAndrewC** [comment]
What data do you need, and in what format?  This would be easy enough for me to do over the weekend, since exporting data is pretty much the easiest type of coding to do :)

**Comment by LowPolyCount** [comment]
stale issue
