### ISSUE TITLE
[Sep 16] Allow Games to be marked as "Alumni" by staff and have an additional text field to fill out for phase 2 submission

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#54]
As staff, let us mark games as being Alumni, meaning the game has been shown at MIVS Before. (Bonus, let us list how many years it's been in) 

During Phase 2, any Alumni game should have an additional textfield that needs to be filled out that says, "Please list what has changed in your game since it was last shown in MIVS" 
They may write up to a paragraph, so textfield should be big enough to accomodate.

**Comment by EliAndrewC** [comment]
Seems doable!

Relatedly: sometime soon, I need to catch up with the MIVS folks about scope and timeline for new features.  I've been kind of MIA for most of the time I said I'd be working to improve the system this year, so we should at least talk through what is and isn't feasible.

**Comment by LowPolyCount** [comment]
Yeah, I was writing these up as I'm sending out an email soon about trying to prioritize things and see what's doable.
