### ISSUE TITLE
Studios submitting multiple games only get email for one game submission 

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#67]
We got a report that a studio that submitted two games but got an email confirmation for one of them after phase 2 had finished.

**Comment by kitsuta** [comment]
This is fairly likely to be a problem outside of the system - for example, their mail client marking one of the mails as Junk, or less likely, Amazon SES failing to send one of the emails. In the future, you can review the emails that the system itself has sent on the https://super2017.uber.magfest.org/uber/emails/ page.

If the email you're talking about has the title, "Your MIVS Game Has Been Submitted," then I can see that the system did indeed send two confirmation emails to the same email address on the same day (about half an hour apart).

**Comment by LowPolyCount** [comment]
We didn't encounter this in 2017, so could have been user error.
