### ISSUE TITLE
[Before SuperMAG] As a paid attendee, I want to be either given a free badge or a refund if I'm assigned as a MIVS judge

### ISSUE THREAD

**Issue by kitsuta** [magfest/mivs#75]
Currently, if someone is created as a MIVS judge but they already have a badge, they are simply given an admin account. However, this means that there is no workflow to refund people who paid for their badge before being assigned as judges. We additionally had a problem this year where someone assumed they'd be getting a second badge and transferred their existing badge (further details in https://github.com/magfest/ubersystem/issues/2118).

There's a bunch of potential ways to create a workflow. Perhaps the most sensible for now is to just check if the existing badge is paid/paid by group with group amount paid, and if so, send an email to the MIVS team _and_ the new judge explaining that a refund is due.

**Comment by EliAndrewC** [comment]
@timrxd: this would be a good next issue to tackle, but you should come talk to me before you start.  There's a similar thing we're doing elsewhere in the codebase that would be a good pattern to reuse that I can show you.
