### ISSUE TITLE
As a STOPS admin, I want new MIVS judges to not be given Staff badge types

### ISSUE THREAD

**Issue by kitsuta** [magfest/mivs#76]
~~NOTE: It is actually currently unclear if this user story is true. Several people I have asked have essentially said "I think we decided we don't want Staff badges for MIVS judges." @bds002 please weigh in.~~

Currently, if a MIVS judge does not already have a badge, a Staff badge is automatically created for them. However, MIVS judges - while they are definitely awarded comped badges - are not automatically volunteering at the fest itself. It would make a lot more sense if they simply had Attendee badges.

**Comment by bds002** [comment]
MIVS Judges are suppose to get Comped Attendee badges for MAGFest 2017. They aren't considered staff unless they ask.  (Aren't eligible for Staff perks).

**Comment by kitsuta** [comment]
Oh, dear. That was never changed, so MIVS judges have been given staff badges so far. It's a bit late for this year, but we'll definitely want to fix this for next year.
