### ISSUE TITLE
[Sep 3] As a Judge, I want a checkbox where I can mark games as having inappropriate content

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#81]

**Comment by kitsuta** [comment]
I can add the checkbox to reviews, but what do you want done with that? Should the judge still have to rate the game? Should it be counted as an 'issue' like the game being unplayable? Should it appear in the reviews summaries? Should it automatically disqualify the game?

**Comment by LowPolyCount** [comment]
A judge should still have to rate the game, It should appear in the reviews summaries
