### ISSUE TITLE
[Aug 20] As a MIVS Volunteer, I need additional data fields that indies can enter about their game so that it's easier for us to get the data for the website and show floor operations

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#89]
This was requested by Jesse for our MIVS terminal that will show game info on the show floor at supermag. We have some of this info collected by the indies now on submission, but need to make sure we have all of it.  

1. Game name
2. SHORT description - 80 characters max
3. 30 sec of best gameplay video - must be youtube hosted, 720p or better.
4. Two best gameplay images - highest res possible (up to 1920x1080). 16:9 preferred but can work with other aspect ratios
5. Studio Name
6. Web / Store link
7. Twitter / other social media link

**Comment by kitsuta** [comment]
While this is technically after prereg, it needs to be done by August 20th. I'm putting it in the Pre-reg epic so I don't lose track of it.

**Comment by smashriot** [comment]
Hey Kitsuta, any update on this uber request or another issue # to track for updates?  thanks!

**Comment by kitsuta** [comment]
Hi @smashriot! This is the correct issue, work just hasn't started on it yet. It'll be the first thing I work on after we launch pre-reg on the 8th (or possibly even before!).

**Comment by smashriot** [comment]
Additionally, we have a few additional bits of information needed to support tournaments for MIVS submissions:

1. Would they like to run a tournament?    yes/no
2. Does there game have a Multiplayer mode?   yes/no
3. How many players are supported? e.g. 2 or 4 players
4. How long does a Multiplayer game last?  e.g. 5 minutes
5. Hi-res cover art or a game logo.  image/link to image
6. Do you have prizes that you would like to distribute?  if so, list them in text.
7. Would you like to run a Leaderboard Challenge?  yes/no

Please let me know if you need clarifications on this mivs support request.  

Thank you for your help!!

**Comment by smashriot** [comment]
Also, we would like the information in the original request for MIVS terminal and the Tournament information to be in a stage 3 (post-acceptance).  e.g. shown/collected to only the studios that were accepted to the MIVS showcase.  

If collecting the information post-acceptance proves to be difficult, adding that information to the 2nd round forms would also suffice.

thank you!

**Comment by RobRuana** [comment]
I've made a new issue out of @smashriot's two most recent comments: https://github.com/magfest/mivs/issues/92
