### ISSUE TITLE
[Oct 14] As an admin, I'd like to be able to unassign a game from a judge

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#94]
This is so if the judge is having issues playing or doesn't have appropriate hardware, we can better keep track of how many judges are assigned to a game.

**Comment by kitsuta** [comment]
Looks like you can already do this on the "Assign Games to [JUDGE]" screen!

![image](https://user-images.githubusercontent.com/7198215/31463760-3a05e64a-ae9d-11e7-88d9-eda41df70ea1.png)

When you click the "Remove" checkbox and then the "Remove" button, the game is unassigned from the judge and the judge's review is deleted.

Is this what you wanted? Was there a problem with it, or is it just confusing that it says "Remove" and not "Unassign"?

**Comment by LowPolyCount** [comment]
This sounds good.
